DROP TABLE league CASCADE CONSTRAINTS;
DROP TABLE team CASCADE CONSTRAINTS;
DROP TABLE player CASCADE CONSTRAINTS;
DROP TABLE stadium CASCADE CONSTRAINTS;
DROP TABLE match CASCADE CONSTRAINTS;
DROP TABLE contract CASCADE CONSTRAINTS;

CREATE TABLE league (
    league_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    league_name VARCHAR(20) NOT NULL,
    league_country VARCHAR(20) NOT NULL,
    league_level NUMBER(2) NOT NULL,
    PRIMARY KEY (league_id)
);

INSERT INTO league (league_name, league_country, league_level) VALUES ('Laliga', 'Spain', 1);
INSERT INTO league (league_name, league_country, league_level) VALUES ('Premier League', 'England', 1);
INSERT INTO league (league_name, league_country, league_level) VALUES ('Ekstraklasa', 'Poland', 1);
INSERT INTO league (league_name, league_country, league_level) VALUES ('Serie B', 'Italy', 2);

CREATE TABLE team (
    team_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    team_name VARCHAR(30) NOT NULL,
    league_id NUMBER(7) NOT NULL,
    PRIMARY KEY (team_id),
    FOREIGN KEY (league_id) REFERENCES league (league_id) ON DELETE CASCADE
);

INSERT INTO team (team_name, league_id) VALUES ('FC Barcelona', 1);
INSERT INTO team (team_name, league_id) VALUES ('Real Madrid', 1);
INSERT INTO team (team_name, league_id) VALUES ('Jagiellonia Bialystok', 3);
INSERT INTO team (team_name, league_id) VALUES ('Manchester United', 2);
INSERT INTO team (team_name, league_id) VALUES ('Palermo', 4);
INSERT INTO team (team_name, league_id) VALUES ('Lech Poznan', 3);
INSERT INTO team (team_name, league_id) VALUES ('Liverpool', 2);
INSERT INTO team (team_name, league_id) VALUES ('Carpi', 4);

CREATE TABLE player (
    player_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    player_name VARCHAR(20) NOT NULL,
    player_surname VARCHAR(20) NOT NULL,
    player_position VARCHAR(20) NOT NULL,
    team_id NUMBER(7) NOT NULL,
    PRIMARY KEY (player_id),
    FOREIGN KEY (team_id) REFERENCES team (team_id) ON DELETE CASCADE
);

INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 0', 'Attack', 1);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 1', 'Attack', 2);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 2', 'Attack', 3);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 3', 'Attack', 4);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 4', 'Attack', 5);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 5', 'Attack', 6);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 6', 'Attack', 7);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Leo', 'Messi 7', 'Attack', 8);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 0', 'Attack', 1);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 1', 'Attack', 2);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 2', 'Attack', 3);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 3', 'Attack', 4);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 4', 'Attack', 5);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 5', 'Attack', 6);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 6', 'Attack', 7);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Cristiano', 'Ronaldo 7', 'Attack', 8);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 0', 'Attack', 1);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 1', 'Attack', 2);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 2', 'Attack', 3);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 3', 'Attack', 4);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 4', 'Attack', 5);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 5', 'Attack', 6);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 6', 'Attack', 7);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Robert', 'Lewandowski 7', 'Attack', 8);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 0', 'Attack', 1);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 1', 'Attack', 2);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 2', 'Attack', 3);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 3', 'Attack', 4);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 4', 'Attack', 5);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 5', 'Attack', 6);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 6', 'Attack', 7);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Ronaldinho', 'Gaucho 7', 'Attack', 8);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 0', 'Goalkeeper', 1);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 1', 'Goalkeeper', 2);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 2', 'Goalkeeper', 3);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 3', 'Goalkeeper', 4);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 4', 'Goalkeeper', 5);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 5', 'Goalkeeper', 6);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 6', 'Goalkeeper', 7);
INSERT INTO player (player_name, player_surname, player_position, team_id) VALUES ('Marian', 'Kelemen 7', 'Goalkeeper', 8);


CREATE TABLE stadium (
    stadium_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    stadium_name VARCHAR(20) NOT NULL,
    stadium_capacity NUMBER(6) NOT NULL,
    stadium_attendance_record NUMBER(6) NOT NULL,
    PRIMARY KEY (stadium_id)
);

INSERT INTO stadium (stadium_name, stadium_capacity, stadium_attendance_record) VALUES ('Camp Nou', 100000, 120000);
INSERT INTO stadium (stadium_name, stadium_capacity, stadium_attendance_record) VALUES ('Santiago Bernabeu', 80000, 90000);
INSERT INTO stadium (stadium_name, stadium_capacity, stadium_attendance_record) VALUES ('Old Trafford', 60000, 62000);
INSERT INTO stadium (stadium_name, stadium_capacity, stadium_attendance_record) VALUES ('Anfield Road', 70000, 70100);
INSERT INTO stadium (stadium_name, stadium_capacity, stadium_attendance_record) VALUES ('Wembley', 97000, 96000);
INSERT INTO stadium (stadium_name, stadium_capacity, stadium_attendance_record) VALUES ('Stamford Birdge', 75000, 76000);

CREATE TABLE match (
    match_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    match_round NUMBER(3) NOT NULL,
    match_home_team_id NUMBER(7) NOT NULL,
    match_away_team_id NUMBER(7) NOT NULL,
    match_home_team_goals NUMBER(2) NOT NULL,
    match_away_team_goals NUMBER(2) NOT NULL,
    stadium_id NUMBER(7) NOT NULL,
    PRIMARY KEY (match_id),
    FOREIGN KEY (match_home_team_id) REFERENCES team (team_id) ON DELETE CASCADE,
    FOREIGN KEY (match_away_team_id) REFERENCES team (team_id) ON DELETE CASCADE,
    FOREIGN KEY (stadium_id) REFERENCES stadium (stadium_id) ON DELETE CASCADE
);

INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 1, 2, 4, 3, 1);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 2, 3, 1, 5, 2);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 3, 4, 2, 3, 3);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 4, 5, 3, 3, 4);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 5, 6, 0, 1, 5);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 6, 7, 0, 0, 6);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 7, 8, 2, 2, 1);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 8, 1, 7, 1, 2);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 1, 3, 3, 1, 3);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 2, 4, 1, 0, 4);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 3, 6, 2, 0, 5);
INSERT INTO match (match_round, match_home_team_id, match_away_team_id, match_home_team_goals, match_away_team_goals, stadium_id) VALUES (1, 4, 7, 2, 2, 6);


CREATE TABLE contract (
    contract_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    player_id NUMBER(7) NOT NULL,
    team_id NUMBER(7) NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_expiration_date DATE NOT NULL,
    PRIMARY KEY (contract_id),
    FOREIGN KEY (player_id) REFERENCES player (player_id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES team (team_id) ON DELETE CASCADE
);

INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (1, 1, TO_DATE('010105', 'MMDDYY'), TO_DATE('010120', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (2, 2, TO_DATE('020105', 'MMDDYY'), TO_DATE('010121', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (3, 3, TO_DATE('030105', 'MMDDYY'), TO_DATE('010122', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (4, 4, TO_DATE('040105', 'MMDDYY'), TO_DATE('010123', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (5, 5, TO_DATE('050105', 'MMDDYY'), TO_DATE('010124', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (6, 6, TO_DATE('060105', 'MMDDYY'), TO_DATE('010125', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (7, 7, TO_DATE('070105', 'MMDDYY'), TO_DATE('010126', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (8, 8, TO_DATE('080105', 'MMDDYY'), TO_DATE('010127', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (9, 1, TO_DATE('090105', 'MMDDYY'), TO_DATE('010128', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (10, 2, TO_DATE('100105', 'MMDDYY'), TO_DATE('010129', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (11, 3, TO_DATE('010105', 'MMDDYY'), TO_DATE('010120', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (12, 4, TO_DATE('020105', 'MMDDYY'), TO_DATE('010121', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (13, 5, TO_DATE('030105', 'MMDDYY'), TO_DATE('010122', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (14, 6, TO_DATE('040105', 'MMDDYY'), TO_DATE('010123', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (15, 7, TO_DATE('050105', 'MMDDYY'), TO_DATE('010124', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (16, 8, TO_DATE('060105', 'MMDDYY'), TO_DATE('010125', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (17, 1, TO_DATE('070105', 'MMDDYY'), TO_DATE('010126', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (18, 2, TO_DATE('080105', 'MMDDYY'), TO_DATE('010127', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (19, 3, TO_DATE('090105', 'MMDDYY'), TO_DATE('010128', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (20, 4, TO_DATE('100105', 'MMDDYY'), TO_DATE('010129', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (21, 5, TO_DATE('010105', 'MMDDYY'), TO_DATE('010120', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (22, 6, TO_DATE('020105', 'MMDDYY'), TO_DATE('010121', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (23, 7, TO_DATE('030105', 'MMDDYY'), TO_DATE('010122', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (24, 8, TO_DATE('040105', 'MMDDYY'), TO_DATE('010123', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (25, 1, TO_DATE('050105', 'MMDDYY'), TO_DATE('010124', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (26, 2, TO_DATE('060105', 'MMDDYY'), TO_DATE('010125', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (27, 3, TO_DATE('070105', 'MMDDYY'), TO_DATE('010126', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (28, 4, TO_DATE('080105', 'MMDDYY'), TO_DATE('010127', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (29, 5, TO_DATE('090105', 'MMDDYY'), TO_DATE('010128', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (30, 6, TO_DATE('100105', 'MMDDYY'), TO_DATE('010129', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (31, 7, TO_DATE('010105', 'MMDDYY'), TO_DATE('010120', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (32, 8, TO_DATE('020105', 'MMDDYY'), TO_DATE('010121', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (33, 1, TO_DATE('030105', 'MMDDYY'), TO_DATE('010122', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (34, 2, TO_DATE('040105', 'MMDDYY'), TO_DATE('010123', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (35, 3, TO_DATE('050105', 'MMDDYY'), TO_DATE('010124', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (36, 4, TO_DATE('060105', 'MMDDYY'), TO_DATE('010125', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (37, 5, TO_DATE('070105', 'MMDDYY'), TO_DATE('010126', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (38, 6, TO_DATE('080105', 'MMDDYY'), TO_DATE('010127', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (39, 7, TO_DATE('090105', 'MMDDYY'), TO_DATE('010128', 'MMDDYY'));
INSERT INTO contract (player_id, team_id, contract_start_date, contract_expiration_date) VALUES (40, 8, TO_DATE('100105', 'MMDDYY'), TO_DATE('010129', 'MMDDYY'));


-- Drużyna nie może grać sama ze sobą

CREATE OR REPLACE TRIGGER check_teams
BEFORE INSERT OR UPDATE ON match
FOR EACH ROW
BEGIN
    IF :NEW.match_home_team_id = :NEW.match_away_team_id THEN
        raise_application_error(-20000,'Team cannot play with itself');
    END IF;
END;
/


-- Zawodnik może mieć kontrakt z maksymalnie jednym zespołem

CREATE OR REPLACE TRIGGER one_player_one_contract
BEFORE INSERT ON contract
FOR EACH ROW
DECLARE
    data_max DATE;
BEGIN
    SELECT data INTO data_max
    FROM (SELECT max(contract_expiration_date) data FROM contract
          WHERE rownum = 1 AND player_id = :NEW.player_id);

    IF :NEW.contract_start_date <= data_max THEN
        raise_application_error(-20000,'Player can not sign new contract with start date before end of the current one');
    END IF;
END;
/
